apiVersion: v1
kind: Secret
metadata:
  name: planner-secret
type: Opaque # Opaque = generic key-value secret (most common type)
data:
  DB_PASSWORD: "cHdk" #Base64 encoded
  MYSQL_PASSWORD: "cHdk" #Base64 encoded
