spring.application.name=service-registry

# default server port for Eureka servers
server.port=8761

# Make sure that this server does not register itself as a client
eureka.client.register-with-eureka=false

# Do not fetch registry for yourself
eureka.client.fetch-registry=false
