apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
    app: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod-lable-name
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod-lable-name
    spec:
      containers:
      - name: nginx-pod-container
        image: nginx:latest
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: 100m
          limits:
            memory: "265Mi"
            cpu: "500m"