spring.application.name=config-server
server.port=8079

# Git config
spring.cloud.config.server.git.uri=https://github.com/Canzova/easybuy-config
spring.cloud.config.server.git.username=canzova
spring.cloud.config.server.git.password={GITHUB_PASSWORD}
spring.cloud.config.server.git.defaultLabel=main

# Encryption
encrypt.key=qwertyuygfxcvbnk98765432qwertyuiugfcxvbnko8765esdfgh

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

management.endpoints.web.exposure.include=*